### ISSUE TITLE
Project.toml file required for newer Julia versions

### ISSUE THREAD

**Issue by ljschumacher** [ananth-pallaseni/EmpiricalBayes.jl#10]
For installing with newer Julia versions it seems a toml file is required instead of using REQUIRE

`(@JuliaPro_v1.5.3-1) pkg> add https://github.com/ananth-pallaseni/EmpiricalBayes.jl
   Updating git-repo `https://github.com/ananth-pallaseni/EmpiricalBayes.jl`
ERROR: could not find project file in package at `https://github.com/ananth-pallaseni/EmpiricalBayes.jl` maybe `subdir` needs to be specified`

**Comment by ljournot** [comment]
Working with Julia 1.6 and unable to install EmpiricalBayes.jl. I get the same message as ljschumacher.

(@v1.6) pkg> add https://github.com/ananth-pallaseni/EmpiricalBayes.jl.git
Updating git-repo `https://github.com/ananth-pallaseni/EmpiricalBayes.jl.git`
ERROR: could not find project file in package at `https://github.com/ananth-pallaseni/EmpiricalBayes.jl.git` maybe `subdir` needs to be specified

Is there another way to install EmpiricalBayes?

Thanks for your help.

**Comment by ananth-pallaseni** [comment]
Thanks both of you for pointing this out! I've just updated the package to work as normal with Pkg (and updated the README to reflect this). Try again, it should work now. Feel free to open another issue if there are still errors.

**Comment by ljschumacher** [comment]
still doesn't work for me, after Pkg.add("EmpiricalBayes") I get
`The following package names could not be resolved:
 * EmpiricalBayes (not found in project, manifest or registry)


Stacktrace:
 [1] pkgerror(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:52
 [2] ensure_resolved(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; registry::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:837
 [3] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.MacOS, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:177
 [4] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:139
 [5] #add#21 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
 [6] add at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
 [7] #add#20 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:66 [inlined]
 [8] add at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:66 [inlined]
 [9] add(::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:65
 [10] add(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:65
 [11] top-level scope at In[3]:1
 [12] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
 [13] execute_code(::String, ::String) at /Users/linus/.julia/packages/IJulia/a1SNk/src/execute_request.jl:27
 [14] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/linus/.julia/packages/IJulia/a1SNk/src/execute_request.jl:86
 [15] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [16] invokelatest at ./essentials.jl:709 [inlined]
 [17] eventloop(::ZMQ.Socket) at /Users/linus/.julia/packages/IJulia/a1SNk/src/eventloop.jl:8
 [18] (::IJulia.var"#15#18")() at ./task.jl:356`

**Comment by ananth-pallaseni** [comment]
EmpiricalBayes is not part of the Julia package registry and so cannot be natively accessed via `Pkg.add`. You have to install it explicitly from this github repo. Instructions are on the README, but you can enter the package manager by entering ']' at the julia prompt, then enter `add https://github.com/ananth-pallaseni/EmpiricalBayes.jl` and this should install the package.

**Comment by ljournot** [comment]
Works fine for me. Thx a lot. Laurent
